# Write your code here :-)
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("    HELLO WORLD              ")
print("    by luke                  ")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("")
print("Hello, World!")
name = input("what is your name? ")
print(f"Hello, {name}")
